spring:
  datasource:
    url: jdbc:postgresql://100.99.252.5:5432/neoanthrop
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false


  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: https://2eae-2401-4900-1f25-626b-c5e2-60e0-c89d-a87d.ngrok-free.app/realms/neo-anthrop

    servlet:
      multipart:
        max-file-size: 150MB
        max-request-size: 150MB

application:
  file:
    uploads:
      media-output-path: ./uploads

springdoc:
  default-produces-media-type: application/json